db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: groot
    MYSQL_DATABASE: study
#  restart: always
  ports:
    - "3306:3306"
  command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']