db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: groot # root 계정 비밀번호
    MYSQL_DATABASE: study # 기본 생성할 데이텀베이스 명
    LC_ALL: C.UTF-8 # 한글 사용 위한 로케일 설정
#  restart: always
  ports:
    - "3306:3306"
  volumes:
#    - ./sql/data:/var/lib/mysql
    - ./scripts:/docker-entrypoint-initdb.d/:ro
  command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']